### ISSUE TITLE
Add package to official package sources

### ISSUE THREAD

**Issue by aparcar** [immortalwrt/openwrt-tmate#1]
Could you please consider adding this package to the official package sources?

**Comment by aparcar** [comment]
https://github.com/openwrt/packages/

**Comment by 1715173329** [comment]
Sorry for missing your issue. In most cases we'll only receive notifications from
immortalwrt/{immortalwrt,luci,packages}, and in other repos you may need to
ping us, or talk it in our [telegram group](https://t.me/ctcgfw_openwrt_discuss) directly.

Already created the PR openwrt/packages#15156.

Thanks,
Tianling.
